// Converts the C rfk_parser table functions (TBL_*) from initcal_tbls.c / dpk_tbls.c / tssi_all.c into a JS
// module. The table bodies are pure bbm/bbset/bbclr/wrf/usleep sequences with identical signatures, so the
// only C-ism to strip is the `u` suffix on hex literals. Logic functions (tssi_live, tssi_tmeter, bbpoll, …)
// are NOT tables and are hand-ported in ax56tx.ts, so only functions named TBL_* are emitted.
const SRC = ["initcal_tbls.c", "dpk_tbls.c", "tssi_all.c"];
const out: string[] = [
  "// GENERATED by gen_ax56tx_tbls.ts from the proven C tables — do not edit by hand.",
  'import { bbm, bbset, bbclr, wrf, usleep } from "./ax56tx_hw.ts";',
  "",
];
const deU = (s: string) => s.replace(/0x([0-9a-fA-F]+)u/g, "0x$1");
let count = 0;
for (const f of SRC) {
  const lines = Deno.readTextFileSync(new URL(f, import.meta.url)).split("\n");
  let cap = false;
  for (const raw of lines) {
    const m = raw.match(/^\s*static void (TBL_\w+)\(void\)\s*\{\s*$/);
    if (m) { out.push(`export function ${m[1]}(){`); cap = true; count++; continue; }
    if (cap) {
      if (raw.trim() === "}") { out.push("}"); cap = false; continue; }
      out.push("  " + deU(raw.trim())); // bbm(...); bbset(...); wrf(...); usleep(...); — identical in JS
    }
  }
}
Deno.writeTextFileSync(new URL("ax56tx_tbls.js", import.meta.url), out.join("\n") + "\n");
console.log(`emitted ${count} TBL_ functions -> ax56tx_tbls.js`);
